version: "3"

networks:
  appnet:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
      - "8081:81"
      - "8443:443"
    command: sh -c 'nginx -g "daemon off;"'
    depends_on:
      - frontend
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c '[ ! -d node_modules ] && pnpm install --force; pnpm run dev'
    networks:
      - appnet
