version: "3"

services:
  # nginx:
  #   build:
  #     context: ./nginx/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ${APP_CODE_PATH_HOST}:/var/www:cached
  #     - ./docker/nginx/sites:/etc/nginx/sites-available
  #     - ./docker/nginx/ssl:/etc/nginx/ssl
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c '[ ! -d node_modules ] && pnpm install --force; pnpm run dev'